version: 2

sources:
  - name: raw
    schema: gz_raw_data

    # freshness: 
    #   warn_after:
    #     count: 90
    #     period: day
    # loaded_at_field: "CAST(date_date AS TIMESTAMP)"

    tables:

      - name: sales
        identifier: raw_gz_sales

        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"

        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key 
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key 
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords

      - name: bing
        identifier: raw_gz_bing

      - name: criteo
        identifier: raw_gz_criteo

      - name: facebook
        identifier: raw_gz_facebook